### ISSUE TITLE
Dependency clash with topic-wizard

### ISSUE THREAD

**Issue by rdkm89** [centre-for-humanities-computing/tweetopic#18]
As discussed in the ML team meeting last week, there is a dependency clash with ```topic-wizard``` related to ```numpy``` versions.

## Expected Behavior

Running ```tweetopic``` and then visualising the results using ```topic-wizard``` should reproduce the kind of output described in the [README.md](https://github.com/centre-for-humanities-computing/tweetopic/blob/725342a4c1dc68cba9be759ea1a1d1d3f07fc221/README.md).

## Current Behavior

In a virtual environment, installing ```tweetopic``` via ```pip``` and then installing ```topic-wizard``` results in the following error:

```bash
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tweetopic 0.2.0 requires numpy<1.23.0,>=1.22.4, but you have numpy 1.24.2 which is incompatible.
tweetopic 0.2.0 requires scikit-learn<1.2.0,>=1.1.1, but you have scikit-learn 1.2.1 which is incompatible.
numba 0.56.4 requires numpy<1.24,>=1.18, but you have numpy 1.24.2 which is incompatible.
```

This means that the workflow outlined in [README.md](https://github.com/centre-for-humanities-computing/tweetopic/blob/725342a4c1dc68cba9be759ea1a1d1d3f07fc221/README.md) is not possible.

(The inverse is obviously the case, if ```topic-wizard``` is installed before ```tweetopic```.)

## Possible Solution

Not a possible solution, but I'm wondering why exactly the two packages require different versions of ```numpy``` in the first place. Have there been breaking changes in ```numpy``` between minor versions which mean that the two packages cannot use the same dependencies? I haven't had a chance to dig into the code, so might be missing something!

## Steps to Reproduce

Error has been reproduced on Ubuntu and MacOS, and for Python versions 3.9, 3.10, and 3.11.

1. ```python3.9 -m venv env```
2. ```pip install --upgrade pip```
3. ```source .env/bin/activate```
4. ```pip install tweetopic```
5. ```pip install topic-wizard```

**Comment by x-tabdeveloping** [comment]
This was mainly an issue with the fact that numba does not support numpy>=1.24 yet, the issue has been fixed by relaxing dependencies on both ends.
If you install the newest version of both packages (preferably tweetopic first) it should work.
