### ISSUE TITLE
Reproducibility and random generators

### ISSUE THREAD

**Issue by niemim** [centre-for-humanities-computing/tweetopic#21]
Setting random seed for numpy.random is not enough to make model fitting reproducible. My experiments indicate that one has to set seed for both numpy and numba (njit) to make DMM model fitting reproducible.

Based on the documentation of numba (https://numba.readthedocs.io/en/stable/reference/pysupported.html#pysupported-random), I added the following code which seems to solve the issue:

`from numba import njit

@njit
def seed(a):
    np.random.seed(a)

np.random.seed(1234)
seed(1234)`

I recommend that this should at least be documented for other users.
I observed this behavior in training DMM models. I have not examined whether it also applies to BTM.

**Comment by x-tabdeveloping** [comment]
I believe this issue is addressed by a new release (version 0.4.0) :)
If you have time please confirm whether it is clear how to reproduce results and if it works as expected on your end.

**Comment by niemim** [comment]
I installed the new version. It is clear, and setting random seed worked as expected.

**Comment by x-tabdeveloping** [comment]
Jolly! I'm closing this then.
