### ISSUE TITLE
set up for sklearn

### ISSUE THREAD

**Issue by KennethEnevoldsen** [centre-for-humanities-computing/tweetopic#5]

**Comment by x-tabdeveloping** [comment]
Done, DMM class is fully compatible with sklearn's NMF and LatentDirichletAllocation API.

**Comment by KennethEnevoldsen** [comment]
Why

**Comment by KennethEnevoldsen** [comment]
Is it, though, why not use sklearn's own pipeline? Seems odd to make your own. I would argue it limits usability.

I also don't see any integration tests ;)

**Comment by x-tabdeveloping** [comment]
I decided to create the TopicPipeline class for ease of use. Pipelines in sklearn can still be used with the model, if one intends to do so, but with TopicPipeline you can use visualize() for easy visualization and top_words() for examining topics. I haven't had time to write a test suite yet, but it's on its way. The DMM class behaves exactly like any other topic model in sklearn, so I kinda consider this done. If someone wants to plug DMM into their own sklearn pipelines, they can do so without any issue (though integration tests will have to  this).

**Comment by KennethEnevoldsen** [comment]
Good arguments - you are very welcome to add me as a reviewer for a pull request if you want the feedback before merging
